# Generated by Django 5.1.1 on 2024-10-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvlblgapp', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=250)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trvlblgapp.register')),
            ],
        ),
    ]
