# Generated by Django 5.1.1 on 2024-10-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trvlblgapp', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback',
        ),
    ]
