# Generated by Django 5.1.1 on 2024-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvlblgapp', '0004_remove_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
