# Generated by Django 5.1.1 on 2024-10-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trvlblgapp', '0005_feedback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
