# Generated by Django 5.1.1 on 2024-10-02 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trvlblgapp', '0006_register_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='dob',
        ),
    ]
